- name: Configuring Backend server
  hosts: backend
  become: yes
  tasks:
    - name: Disable nodejs old version
      ansible.builtin.command: "dnf module disable nodejs -y"
    - name: Enable nodejs 20 version
      ansible.builtin.command: "dnf module enable nodejs:20 -y"
    - name: Installing Node Js
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: Creating Expense user
      ansible.builtin.user:
        name: expense
    - name: Create App Directory
      ansible.builtin.file:
        name: /app
        state: directory
