- name: Configuring Backend server
  hosts: backend
  become: yes
  tasks:
    - name: Disable nodejs old version
      ansible.builtin.command: "dnf module disable nodejs -y"
    - name: Enable nodejs 20 version
      ansible.builtin.command: "dnf module enable nodejs:20 -y"
    - name: Installing Node Js
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: Creating Expense user
      ansible.builtin.user:
        name: expense
    - name: Create App Directory
      ansible.builtin.file:
        name: /app
        state: directory
    - name: Download the backend code.
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: Unzipping backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    - name: Install Dependencies
      community.general.npm:
        path: /app
    - name: Copying Backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
