- name: configuring mysql server
  hosts: database
  become: yes
  tasks:
    - name: installing MySQL Dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - cryptography
        - PyMySQL
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: installed
    - name: Starting and Enabling MySQL server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Connect to My SQL server
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: database.sridevsecops.store
      register: mysql_info
      ignore_errors: true
    - name: Print the output
      ansible.builtin.debug:
        msg: "MySQL Info is : {{ mysql_info }}"
    - name: Set Root login_password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
      when: mysql_info.failed is true
